### PR TITLE
Revert "[MMM-Spotify.js] Add FA Icons | Custom Icons by Device Type | Album Info | Modularize Code"

### PR DESCRIPTION
**Pull request by bugsounet**
Reverts bugsounet/MMM-Spotify#51

### CODE REVIEW

**Comment by humbertovirtudes** [comment]
what happened?

**Comment by bugsounet** [comment]
don't know... module don't show

**Comment by bugsounet** [comment]
revert is the same

**Comment by bugsounet** [comment]
can you remake your PR in dev branch plz ?
I will inspect
Actually spotify website not respond

**Comment by humbertovirtudes** [comment]
I think you just reverted the revert. lemme know if you need help
debugging. Also I love to collaborate in building/improving more modules :D

**Comment by bugsounet** [comment]
there is no problem :)

i have just a black screen because Spotify don't repond ... and i test with spotify website and it's the same

now it works ;)

yes i see some bug, i have to solve it (minor, but take fatal error...)
and i have to make (maybe) some translate file for 'listening on'

**Comment by humbertovirtudes** [comment]
Cool - Im working on adding support for all device icons (theres a few on
the API)

Then I wanna make smth to make authentication smoother

**Comment by humbertovirtudes** [comment]
Its not working for me now - :(

**Comment by bugsounet** [comment]
don't know why, i have to recreate the token when it not works

**Comment by humbertovirtudes** [comment]
Does it happen often?

**Comment by humbertovirtudes** [comment]
Is you rmagic mirror just freezing every couple of hours or so?

**Pull request merged**
