### PR TITLE
Multiple accounts support

### PR DESCRIPTION
**Pull request by aarizkuren**
Hi, 
I've added the option to use more than one linked spotify account in this module. For example, in my house we are two people, each with his account. So, now it shows the information of the active account of both. This way we can see what we are playing from either one of them.

I've done it for my own consumption, but I'm sending you the pull request in case you find it interesting.

Greetings and thanks for all your work!

### CODE REVIEW

**Comment by eouia** [comment]
thanks for contribution.
to get token, does each account need same config?

**Comment by aarizkuren** [comment]
Hi!
No, each user has to use his own login data, his client_id and his client_secret. The other configuration options can be the same.

**Comment by eouia** [comment]
Someone reports https://github.com/eouia/MMM-Spotify/issues/36
It seems to be related with this commit. Can you inspect this?

**Comment by bugsounet** [comment]
I really don't think that multi-account is a good feature ...
there is a so buggy part when playing in multi-account.
actually node_helper code return `this.sendSocketNotification("CURRENT_PLAYBACK_FAIL");`
when an account is not playing it's creating a loop...

**Pull request merged**
